Source/SironaTeleMedClient/Controllers/AppointmentController.cs
using SironaTeleMed.Entities.Contract;
using SironaTeleMedClient.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using SironaTeleMed.Common.Paging;
using SironaTeleMed.Entities.V1;
using SironaTeleMed.Services.Contract;
using SironaTeleMedClient.Pages;
using System.Web;
using System.Web.Mvc;
using SironaTeleMed.Common;
using DataTables.Mvc;
using System.IO;
using Twilio;
using Twilio.Rest.Video.V1;
using Stripe;
using System.Configuration;
using System.Xml.Serialization;
using System.Net.Http;
using System.Text;
using System.Xml;
using static SironaTeleMedClient.Infrastructure.Enums;
using System.Threading.Tasks;
using System.Net;
using System.Data;
using System.Data.SqlClient;

namespace SironaTeleMedClient.Controllers
{
    public class AppointmentController : BaseController
    {
        private readonly AbstractUsersService usersService;
        private readonly AbstractSessionsServices sessionsService;
        private readonly AbstractSessionScheduleServices sessionsScheduleService;
        private readonly AbstractSessionDocumentServices sessionDocumentServices;

        public AppointmentController(AbstractUsersService usersService, AbstractSessionsServices sessionsService, AbstractSessionScheduleServices sessionsScheduleService, AbstractSessionDocumentServices sessionDocumentServices)
        {
            this.usersService = usersService;
            this.sessionsService = sessionsService;
            this.sessionsScheduleService = sessionsScheduleService;
            this.sessionDocumentServices = sessionDocumentServices;
        }

        [HttpGet]
        public ActionResult BookAppointments(int id, int SSid = 0)
        {
            AbstractSessions sessions = new Sessions();
            if (id == 0)
            {
                PageParam pageParam = new PageParam();
                sessions.SessionScheduleId = SSid;
                var sessionschedule = sessionsScheduleService.SessionScheduleSelect(sessions.SessionScheduleId);
                if (sessionschedule != null)
                {
                    sessions.SessionStart = sessionschedule.Item.SessionStart;
                }
                return View(sessions);
            }
            else
            {
                sessions = sessionsService.SessionsSelect(id).Item;
                sessions.UserDescription = sessions.UUserDescription;
                sessions.SpecialRequests = sessions.SSpecialRequests;
                sessions.DoctorComments = sessions.DDoctorComments;
                sessions.DoctorComments2 = sessions.DDoctorComments2;
                sessions.DoctorComments3 = sessions.DDoctorComments3;
                sessions.DoctorComments4 = sessions.DDoctorComments4;
                if (sessions == null)
                {
                    return HttpNotFound();
                }
                return View(sessions);
            }
        }

        [HttpGet]
        public JsonResult UpdateIsMessage()
        {
            if (ProjectSession.IsMsg == "1")
            {
                ProjectSession.IsMsg = "0";
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult DoctorAppointment(int id, int SSid = 0)
        {
            AbstractSessions sessions = new Sessions();
            if (id == 0)
            {
                PageParam pageParam = new PageParam();
                sessions.SessionScheduleId = SSid;
                var sessionschedule = sessionsScheduleService.SessionScheduleSelect(sessions.SessionScheduleId);
                if (sessionschedule != null)
                {
                    sessions.SessionStart = sessionschedule.Item.SessionStart;
                }
                return View(sessions);
            }
            else
            {
                sessions = sessionsService.SessionsSelect(id).Item;
                sessions.UserDescription = sessions.UUserDescription;
                sessions.SpecialRequests = sessions.SSpecialRequests;
                sessions.DoctorComments = sessions.DDoctorComments;
                sessions.DoctorComments2 = sessions.DDoctorComments2;
                sessions.DoctorComments3 = sessions.DDoctorComments3;
                sessions.DoctorComments4 = sessions.DDoctorComments4;
                if (sessions == null)
                {
                    return HttpNotFound();
                }
                sessions.RxInput = "-";
                if(sessions.StatusId == 10)
                {
                    DataTable dtp = new DataTable();
                    DataTable dtd = new DataTable();
                    SqlConnection con = new SqlConnection(Configurations.ConnectionString);
                    string var_sql = "select U.*,MS.State as StateName from Users U left join MasterState MS on U.StateId=MS.Id where U.Id = " + sessions.UserId;
                    SqlDataAdapter sda = new SqlDataAdapter(var_sql, con);
                    sda.Fill(dtp);

                    var_sql = "select U.*,MS.State as StateName,MSD.State as LicenseStateName from Users U left join MasterState MS on U.StateId=MS.Id left join MasterStates MSD on U.Doctorlicensestate=MSD.Id where U.Id = " + sessions.AssignedTo;
                    SqlDataAdapter sdad = new SqlDataAdapter(var_sql, con);
                    sdad.Fill(dtd);

                    if(dtp.Rows.Count > 0 && dtd.Rows.Count > 0)
                    {
                        string tempPrescription = "<NCScript xmlns='http://secure.newcropaccounts.com/interfaceV7' xmlns:NCStandard='http://secure.newcropaccounts.com/interfaceV7:NCStandard' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><Credentials><partnerName>@partnername</partnerName><name>@name</name><password>@password</password><productName>@productname</productName><productVersion>@productversion</productVersion></Credentials><UserRole><user>@user</user><role>@role</role></UserRole><Destination><requestedPage>@requestedpage</requestedPage></Destination><Account ID='demo'><accountName>@accountname</accountName><siteID>@siteId</siteID><AccountAddress><address1>@customeraddress1</address1><address2>@customeraddress2</address2><city>@customercity</city><state>@customerstate</state><zip>@customerzip</zip><country>@customercountry</country></AccountAddress><accountPrimaryPhoneNumber>@accountprimaryphonenumber</accountPrimaryPhoneNumber><accountPrimaryFaxNumber>@accountprimaryfaxnumber</accountPrimaryFaxNumber></Account>";
                        tempPrescription += "<Location ID='DEMOLOC1'><locationName>@customerLocation</locationName><LocationAddress><address1>@customeraddress1</address1><address2>@customeraddress2</address2><city>@customercity</city><state>@customerstate</state><zip>@customerzip</zip><country>@customercountry</country></LocationAddress><primaryPhoneNumber>@primaryphonenumber</primaryPhoneNumber><primaryFaxNumber>@primaryfaxnumber</primaryFaxNumber><pharmacyContactNumber>@pharmacycontactnumber</pharmacyContactNumber></Location>";
                        tempPrescription += "<LicensedPrescriber ID='DEMOLP1'><LicensedPrescriberName><last>@doctorlastname</last><first>@doctorfirstname</first><middle>@doctormiddlename</middle></LicensedPrescriberName><dea>@dea</dea><upin>@upin</upin><licenseState>@doctorlicensestate</licenseState><licenseNumber>@doctorlicensenumber</licenseNumber><npi/></LicensedPrescriber>";
                        tempPrescription += "<Patient ID='DEMOPT1'><PatientName><last>@customerlastname</last><first>@customerfirtname</first><middle>@customermiddlename</middle></PatientName><medicalRecordNumber>@medicalrecordnumber</medicalRecordNumber><memo>@memo</memo><PatientAddress><address1>@customeraddress1</address1><address2>@customeraddress2</address2><city>@customercity</city><state>@customerstate</state><zip>@customerzip</zip><country>@customercountry</country></PatientAddress>";
                        tempPrescription += "<PatientContact><homeTelephone>@hometelephone</homeTelephone></PatientContact><PatientCharacteristics><dob>@dob</dob><gender>@gender</gender></PatientCharacteristics></Patient></NCScript>";


                        tempPrescription = tempPrescription.Replace("@partnername", "demo");
                        tempPrescription = tempPrescription.Replace("@name", "demo");
                        tempPrescription = tempPrescription.Replace("@password", "demo");
                        tempPrescription = tempPrescription.Replace("@productname", "SuperDuperSoftware");
                        tempPrescription = tempPrescription.Replace("@productversion", "V5.3");
                        tempPrescription = tempPrescription.Replace("@user", "LicensedPrescriber");
                        tempPrescription = tempPrescription.Replace("@requestedpage", "compose");
                        tempPrescription = tempPrescription.Replace("@role", "doctor");
                        tempPrescription = tempPrescription.Replace("@accountname", "Your Customer's Account Name");
                        tempPrescription = tempPrescription.Replace("@siteId", "demo");

                        tempPrescription = tempPrescription.Replace("@customeraddress1", Convert.ToString(dtp.Rows[0]["Address"]));
                        tempPrescription = tempPrescription.Replace("@customeraddress2", Convert.ToString(dtp.Rows[0]["AddressLine2"]));
                        tempPrescription = tempPrescription.Replace("@customercity", Convert.ToString(dtp.Rows[0]["City"]));
                        tempPrescription = tempPrescription.Replace("@customerstate", Convert.ToString(dtp.Rows[0]["StateName"]));
                        tempPrescription = tempPrescription.Replace("@customerzip", Convert.ToString(dtp.Rows[0]["CountryId"]));
                        //tempPrescription = tempPrescription.Replace("@zip4", "1234");
                        tempPrescription = tempPrescription.Replace("@customercountry", "US");

Source/SironaTeleMedClient/Controllers/BookNowController.cs
using SironaTeleMed.Entities.Contract;
using SironaTeleMed.Entities.V1;
using SironaTeleMed.Services.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SironaTeleMedClient.Controllers
{
    public class BookNowController : Controller
    {
        private readonly AbstractSessionScheduleServices sessionsScheduleService;
        public BookNowController(AbstractSessionScheduleServices sessionsScheduleService)
        {
            this.sessionsScheduleService = sessionsScheduleService;
        }

        // GET: BookNow
        public ActionResult Index()
        {
            AbstractIndexMaster abstractIndexMaster = new IndexMaster();
            List<AbstractSessionSchedule> sessionSchedule = new List<AbstractSessionSchedule>();// new List<SessionSchedule>();
            var sessionsSchedules = sessionsScheduleService.SearchSessionsSelectByDate(DateTime.Now.ToString("dd/MM/yyyy"));
            if (sessionsSchedules.Values.Count() > 0)
            {
                abstractIndexMaster.abstractSessionSchedules = sessionsSchedules.Values;
            }
            return View(abstractIndexMaster);
        }

        [HttpPost]
        public ActionResult _SearchSessions(string date)
        {
            AbstractIndexMaster abstractIndexMaster = new IndexMaster();
            List<AbstractSessionSchedule> sessionSchedule = new List<AbstractSessionSchedule>();// new List<SessionSchedule>();
            var sessions = sessionsScheduleService.SearchSessionsSelectByDate(date);
            if (sessions.Values.Count() > 0)
            {
                abstractIndexMaster.abstractSessionSchedules = sessions.Values;
            }
            return PartialView(abstractIndexMaster);
        }

    }
}

Source/SironaTeleMedClient/Controllers/HomeController.cs
using DataTables.Mvc;
using SironaTeleMed.Common;
using SironaTeleMed.Common.Paging;
using SironaTeleMed.Entities.Contract;
using SironaTeleMed.Entities.V1;
using SironaTeleMed.Services.Contract;
using SironaTeleMedClient.Infrastructure;
//using SironaTeleMed.Infrastructure;
using SironaTeleMedClient.Pages;
using Square.Connect.Api;
using Square.Connect.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
//using static SironaTeleMed.Infrastructure.Enums;
using System.Web;
using System.Web.Mvc;

namespace SironaTeleMedClient.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/SironaTeleMedClient/Views/Home/BookNow.cshtml
@using SironaTeleMedClient.Pages;
@using SironaTeleMed.Common;
@using SironaTeleMed.Entities.Contract

@{
    ViewBag.Title = "SearchSessions";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}
@model AbstractIndexMaster

<div class="container">
    <div class="row">
        <div class="col-12 mt-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card_title mt-2">Search Appointments</h4>
                    <div class="card-body">
                        <div class="form-row">
                            <div class="col-md-3 mb-3">
                                <div class="input-group form-group">
                                    <input type="text" id="searchdate" class="form-control" name="dateselect" />
                                    <div class="input-group-append" style="display:flex;">
                                        <span class="input-group-text" style="display: flex;background-color: #f9f9f9 !important;border-radius: .25rem;border: 1px solid rgba(170, 170, 170, 0.3) !important;padding: .495rem .75rem;">
                                            <i class="fa fa-calendar" aria-hidden="true"></i>
										</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
							    <button id="div2" type="submit" class="btn" style="background: #00B3FF !important;color: #fff">
                                    Search
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="ap-tmng" id="partial">
                        @Html.Partial("_SearchSessions")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .ap-timers {
        background: #e3e3e3;
        padding: 20px 15px;
        display: inline-block;
    }
    .ap-timers ul {
        padding: 0;
        margin: 0;
        width: 100%;
        list-style: square;
    }
    .ap-timers ul li {
        position: relative;
        display: inline-block;
        margin-right: 15px;
        margin-bottom: 25px;
    }
    .ap-timers ul li a {
        width: 100%;
        background: #fff;
        border-radius: 5px;
        padding: 8px 15px;
        color: #1a2c3f;
        font-size: 14px;
        text-decoration: none;
        border: 1px solid #dfdfdf;
    }
    .ap-timers ul li a:hover {
        background: #cccccc;
    }
</style>

Source/SironaTeleMedClient/Views/Home/_SearchSessions.cshtml
@using SironaTeleMed.Entities.Contract;
@{
    ViewBag.Title = "SearchSessions";
}

@model AbstractIndexMaster

<div class="ap-timers text-center" style="width: 100%">
    <h2>Appointment Timings</h2>
    <br>
    <ul>
        @if (Model != null && Model.abstractSessionSchedules != null && Model.abstractSessionSchedules.Count() > 0)
        {
            foreach (var item in Model.abstractSessionSchedules)
            {
                <li style="line-height:30px;width:130px">
                    <a href=@Url.Action("BookAppointments", "Appointment", new { area = "", id = 0 , SSid =  item.Id  }) style="font-size: 16px; border: 2px solid #00B3FF;">@item.AppointMentDate</a>
                </li>
            }
        }
        else
        {
            <li><a style="font-size: 16px; border: 2px solid #00B3FF;">No Appointments Found !</a></li>
        }
    </ul>
</div>