Source/SironaTeleMedWebsite/Controllers/ContactUsController.cs
using SironaTeleMed.Common;
using SironaTeleMed.Entities.V1;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SironaTeleMedWebsite.Controllers
{
    public class ContactUsController : Controller
    {

        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ThankYou()
        {
            return View();
        }

        [HttpPost]
        public ActionResult WebContact(WebContactUs webContactUs)
        {
            if (ModelState.IsValid)
            {
                string staticEmail = "devplexoc@gmail.com";

                if (webContactUs.Email != "")
                {
                    string body = string.Empty;
                    body = "<html>" +
                            "<head></head>" +
                            "<body>" +
                            "<h4>Name : " + webContactUs.Name + "</h4>" +
                            "<h4>Email : " + webContactUs.Email + "</h4>" +
                            "<h4>Phone : " + webContactUs.Phone + "</h4>" +
                            "<h4>Subject : " + webContactUs.Subject + "</h4>" +
                            "<h4>Messsage : " + webContactUs.Message + "</h4>" +
                            "</body>" +
                            "</html>";
                    string mailFrom = webContactUs.Email;
                    EmailHelper.Send(staticEmail, "", "", "New Inquiry", body);
                }
                return RedirectToAction("ThankYou", "ContactUs");
            }
            else
            {
                return RedirectToAction("Index", "ContactUs");
            }
        }
    }
}

Source/SironaTeleMedWebsite/Controllers/FaqController.cs
using System.Web.Mvc;

namespace SironaTeleMedWebsite.Controllers
{
    public class FaqController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/SironaTeleMedWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SironaTeleMedWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        
    }
}

Source/SironaTeleMedWebsite/Controllers/HowWeWorkController.cs
using System.Web.Mvc;

namespace SironaTeleMedWebsite.Controllers
{
    public class HowWeWorkController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/SironaTeleMedWebsite/Controllers/PricingController.cs
using System.Web.Mvc;

namespace SironaTeleMedWebsite.Controllers
{
    public class PricingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/SironaTeleMedWebsite/Views/ContactUs/Index.cshtml
@using SironaTeleMed.Entities.V1;
@using SironaTeleMed.Common;

@{
    ViewBag.Title = "Contact Us";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

@model WebContactUs

<style>
    .ulockd-contact-form .ulockd-form-fg {
        margin-bottom: 0px;
    }
</style>
<!-- Home Design Inner Pages -->
<div class="ulockd-inner-home">
    <div class="container">
        <div class="row">
            <div class="inner-conraimer-details">
                <div class="col-md-12">
                    <h1 class="text-uppercase">CONTACT US</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Home Design Inner Pages -->
<div class="ulockd-inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-icd-layer">
                    <ul class="list-inline ulockd-icd-sub-menu">
                        <li><a href="@Url.Action("Index", "Home")"> HOME </a></li>
                        <li><a href="#"> > </a></li>
                        <li> <a href="#"> CONTACT US </a> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Inner Pages Main Section -->
<section class="ulockd-contact-page">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="ulockd-main-title">
                    <h2 class="mt-separator">Contact Details</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3">
                <div class="ulockd-ohour-info style2 text-center">
                    <div class="ulockd-icon text-thm2"><span class="fa fa-phone"></span></div>
                    <div class="ulockd-info">
                        <h3>Call Us</h3>
                        <p class="ulockd-addrss">+98 9875 5968 54</p>
                    </div>
                </div>
            </div>
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3">
                <div class="ulockd-ohour-info style2 text-center">
                    <div class="ulockd-icon text-thm2"><span class="fa fa-map-signs"></span></div>
                    <div class="ulockd-info">
                        <h3>Address</h3>
                        <p>Four infity loop Av. 45635</p>
                    </div>
                </div>
            </div>
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3">
                <div class="ulockd-ohour-info style2 mb305-xsd text-center">
                    <div class="ulockd-icon text-thm2"><span class="fa fa-edit"></span></div>
                    <div class="ulockd-info">
                        <h3>Mail Us</h3>
                        <p class="ulockd-addrss"><strong>Email:</strong> Left Some Word</p>
                    </div>
                </div>
            </div>
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3">
                <div class="ulockd-ohour-info style2 text-center">
                    <div class="ulockd-icon text-thm2"><span class="icon-Envelope"></span></div>
                    <div class="ulockd-info">
                        <h3>Mail Us</h3>
                        <p class="ulockd-addrss"><strong>Email:</strong> dummy2@yourmail.com</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row ulockd-mrgn1250">
            <div class="col-md-12">
                <div class="ulockd-contact-form">
                    @using (Html.BeginForm("WebContact", "ContactUs", FormMethod.Post, new { @id = "contact-form", @class = "contact-form", @novalidate = "" }))
                    {
                        <h5 style="text-align:center;color:red;">@ViewBag.ErrorMessage</h5>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Name, new { maxlength = 100, @class = "form-control ulockd-form-fg", @required = "", placeholder = "Your Name" })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Email, new { maxlength = 100, @class = "form-control ulockd-form-fg", @required = "", placeholder = "Your Email" })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Phone, new { maxlength = 100, @class = "form-control ulockd-form-fg", @required = "", placeholder = "Phone", @Type = "number" })
                                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="form-group">
                                    @Html.TextBoxFor(model => model.Subject, new { maxlength = 100, @class = "form-control ulockd-form-fg", @required = "", placeholder = "Subject" })
                                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    @Html.TextAreaFor(model => model.Message, new { rows = 12, @class = "form-control ulockd-form-fg", @required = "", placeholder = "Your Message" })
                                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group ulockd-contact-btn">
                                    <input id="form_botcheck" name="form_botcheck" class="form-control" value="" type="hidden">
                                    <button type="submit" class="btn btn-default ulockd-btn-thm2" data-loading-text="Getting Few Sec...">SUBMIT</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid ulockd-padz">
        <div class="row">
            <div class="col-md-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7342.854947836821!2d72.50440389382783!3d23.04478459361963!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xa3f18c24ae12aa29!2sTime%20Square%202!5e0!3m2!1sen!2sin!4v1569304556616!5m2!1sen!2sin" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>
</section>

<!-- Our Partner -->
<section class="unlock-divider ulockd-bgthm">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/client/partners/1.png" alt="1.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/client/partners/2.png" alt="2.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/client/partners/3.png" alt="3.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/client/partners/4.png" alt="4.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/client/partners/5.png" alt="5.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/client/partners/6.png" alt="6.png"></div></div>
        </div>
    </div>
</section>

Source/SironaTeleMedWebsite/Views/ContactUs/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-6">
        <h1 style="color: #00ACFF;">Thank you for Contacting Us</h1>
    </div>
</div>

Source/SironaTeleMedWebsite/Views/Faq/Index.cshtml
@{
    ViewBag.Title = "FAQ";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
}


<!-- Home Design Inner Pages -->
<div class="ulockd-inner-home">
    <div class="container">
        <div class="row">
            <div class="inner-conraimer-details">
                <div class="col-md-12">
                    <h1 class="text-uppercase">Faq</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Home Design Inner Pages -->
<div class="ulockd-inner-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="ulockd-icd-layer">
                    <ul class="list-inline ulockd-icd-sub-menu">
                        <li><a href="@Url.Action("Index", "Home")"> HOME </a></li>
                        <li><a href="#"> > </a></li>
                        <li> <a href="#"> Faq </a> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Our About Page faq Section -->
<section class="ulockd-ap-faq">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-7">
                <div class="ulockd-faq-box">
                    <div class="ulockd-faq-title clearfix">
                        <h2>Frequently Asked  <span class="text-thm2">Questions</span></h2>
                    </div>
                    <div class="ulockd-faq-content">
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingOne">
                                    <h4 class="panel-title">
                                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            <i class="icon-Down-2 icon-1"></i>
                                            <i class="icon-Right-2 icon-2"></i>
                                            How Can I Contact For Support?
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                    <div class="panel-body">
                                        <p>Go to Our Profile Page <a href="https://themeforest.net/user/unlockdesign">Here..</a>, Mail Us. As Soon As Possible In Our Supported Schdule We will reply you.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingTwo">
                                    <h4 class="panel-title">
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            <i class="icon-Down-2 icon-1"></i>
                                            <i class="icon-Right-2 icon-2"></i>
                                            Contact Form Active?
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                    <div class="panel-body">
                                        <p>Sure, You Will Get Contact Form Active In Our All Templates, Just go to Include Folder contact.php Change You Mail id in Demo Mail Id Then Run Your Tempalte.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingThree">
                                    <h4 class="panel-title">
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                            <i class="icon-Down-2 icon-1"></i>
                                            <i class="icon-Right-2 icon-2"></i>
                                            About Sirona Tele Med Education Template?
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                    <div class="panel-body">
                                        <p>Yes. Administrations are accessible for as meager as a couple of hours a visit up to 24 hours, 7 days seven days, 365 days a year.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headignFour">
                                    <h4 class="panel-title">
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                            <i class="icon-Down-2 icon-1"></i>
                                            <i class="icon-Right-2 icon-2"></i>
                                            What is Primary Care?
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headignFour">
                                    <div class="panel-body">
                                        <p>The term essential care alludes to the sort of restorative care you require first — before you become ill, before you have to see a master, before you have to go to a healing facility.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headignFive">
                                    <h4 class="panel-title">
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                                            <i class="icon-Down-2 icon-1"></i>
                                            <i class="icon-Right-2 icon-2"></i>
                                            What if my Comfort Keeper is sick or on vacation?
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headignFive">
                                    <div class="panel-body">
                                        <p>Each Comfort Keepers office utilizes a group of parental figures so that your care administration won't be hindered in the event that somebody becomes ill or takes some time off. In the event that your Comfort Keeper is inaccessible, the Client Care Coordinator will organize another parental figure and will reach you ahead of time of the change.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headignSix">
                                    <h4 class="panel-title">
                                        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                                            <i class="icon-Down-2 icon-1"></i>
                                            <i class="icon-Right-2 icon-2"></i>
                                            Is long term care expensive?
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headignSix">
                                    <div class="panel-body">
                                        <p>It can be. Americans burn through billions of dollars a year on different administrations. How much an individual pays relies on upon the sort and measure of administrations gave, where he or she lives, regardless of whether family and companions can give care, and which paid suppliers are utilized.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-5">
                <h2 class="ulockd-mrgn120">Sirona Tele Med <span class="text-thm2">Activity</span></h2>
                <div class="ulockd-about-video ulockd-mrgn1225">
                    <div class="ulockd-avdo-thumb">
                        <iframe width="100%" height="465px" src="http://www.youtube.com/embed/qKoVto0Wegg?autoplay=0" allowfullscreen=""></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Our Partner -->
<section class="unlock-divider ulockd-bgthm">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/Client/partners/1.png" alt="1.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/Client/partners/2.png" alt="2.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/Client/partners/3.png" alt="3.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/Client/partners/4.png" alt="4.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/Client/partners/5.png" alt="5.png"></div></div>
            <div class="col-xs-6 col-sm-4 col-md-2"><div class="ulockd-divider-thumb text-center bgc-white"><img src="~/images/Client/partners/6.png" alt="6.png"></div></div>
        </div>
    </div>
</section>

Source/SironaTeleMedWebsite/Views/Shared/_ClientFooter.cshtml
    <div class="container footer-padding">
        <div class="row">
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3 col-lg-4">
                <div class="footer-fst-col">
                    <div class="footer-logo ulockd-mrgn620 ulockd-mrgn1215"><img class="ulockd-footer-log img-responsive" src="~/images/Client/header-logo.png" alt="header-logo.png"></div>
                    <p>Regardless of whether you need to stay in your own house, are searching for help with a more established relative, looking for exhortation on paying for care, we can help you.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci inventore sit consequuntur incidunt ipsum iusto?</p>
                    <div class="ulockd-footer-newsletter">
                        <h3>News Letter</h3>
                        <form class="ulockd-mailchimp style2">
                            <div class="input-group">
                                <input type="email" class="form-control input-md bgc-snowshade2" placeholder="Your email" name="EMAIL" value="">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-md"><i class="icon fa fa-chevron-right"></i></button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3 col-lg-2">
                <div class="footer-qlink mb35-smd">
                    <h3 class="text-uppercase"><span class="color-black33">NAVIGATION</span></h3>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li><a href="@Url.Action("Index", "HowWeWork")">How we Work</a></li>
                        <li><a href="@Url.Action("Index", "Pricing")">Pricing</a></li>
                        <li><a href="@Url.Action("Index", "Faq")">FAQ</a></li>
                        <li><a href="@Url.Action("Index", "ContactUs")">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <div class="footer-contact">
                    <h3 class="text-uppercase"><span class="color-black33">CONTACT US</span></h3>
                    <p>Victoria 8007 Australia Envato HQ 121 King Street, Melbourne.</p>
                    <div class="ftr-phone"><span>Phone </span>: <a href="#"> 99 55 66 88 526</a></div>
                    <div class="ftr-fax"><span>Fax </span>: <a href="#"> 55 44 77 62</a></div>
                    <div class="ftr-mail"><span>Email </span>: <a href="#"> CHeart@email.com</a></div>
                    <div class="ftr-mail"><span>Website </span>: <a href="#"> https://envato.com/</a></div>
                    <div class="ftr-mail"><span>Website </span>: <a href="#"> https://themeforest.net/</a></div>
                    <div class="ftr-mail"><span>Website </span>: <a href="#"> https://codecanyon.net/</a></div>
                    <ul class="list-inline footer-font-icon style2 ulockd-mrgn1215">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-feed"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xxs-12 col-xs-6 col-sm-6 col-md-3 col-lg-3">
                <div class="footer-twitter">
                    <h3 class="text-uppercase"><span class="color-black33">TWITTER FEEDS</span></h3>
                    <div class="twitter style2"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="ulockd-copy-right">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="color-white">Sirona Tele Med's Copyright© 2018. All right reserved.</p>
                </div>
            </div>
        </div>
    </div>

Source/SironaTeleMedWebsite/Views/Shared/_ClientMenu.cshtml
<!--=========================*
    Client Menu
    *===========================-->
<!-- Header Styles -->
<style>
    .flright{
        float: right !important;
    }
    
</style>
<header class="header-nav">
    <div class="main-header-nav navbar-scrolltofixed">
        <div class="container">
            <!-- Start Navigation -->
            <nav class="navbar navbar-default bootsnav menu-style1">

               
                <div class="container">
                    <!-- End Header Navigation -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="navbar-menu">
                        <ul class="nav navbar-nav navbar-left" data-in="fadeIn" style="width: 100%;">
                            <li>
                                <a href="@Url.Action("Index", "Home")">Home</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "HowWeWork")">How We Work</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Pricing")">Pricing</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Faq")">FAQ</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "ContactUs")">Contact Us</a>
                            </li>
                            
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div>

                
            </nav>
            <!-- End Navigation -->
        </div>
    </div>
</header>

Source/SironaTeleMedWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>